/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 silvers.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/silvers2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Silver_Surfer.geometry} 
        material={materials['Material.002']} 
        position={[0, .5, 0]} 
        rotation={[-0.552, 0, 0]} 
        scale={0.03 }
      >
        <meshStandardMaterial 
          attach="material"
          color="silver" 
          roughness={0.2}   
          metalness={1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/silvers2.glb')
